name: Feathers build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: cp feathers/.env ~/actions-runner/_work/onbai-feathers/onbai-feathers
      - run: npm install
      - run: pm2 restart be --update-env
